#! /bin/bash

set -eo pipefail

#
# download data
#

. ~/.bash_aliases
shopt -s expand_aliases

ciao -o

. src/functions.bash

# list of obsids
obsids=$(obsids)

mkdir -p $datadir
cd $datadir
for o in $obsids
do
  download_chandra_obsid $o mtl,evt1,asol,msk,flt,dtf 2>&1
done
