#! /bin/bash

set -eo pipefail

i=$1
n=$2

. ~/.bash_aliases
shopt -s expand_aliases

ciao -o

. src/functions.bash
. /data/legs/rpete/flight/analysis_functions/tmppdir.bash

tg_reprocess=/data/legs/rpete/flight/devel/tg_reprocess

# list of obsids
obsids=$(obsids)

# whether to force reprocessing if tg_reprocess output already exists
force=1

for o in $obsids
do
    dir=$datadir/$o
    outdir=$dir/tg_reprocess

    [ -f $outdir/*_evt2.fits -a $force -eq 0 ] && continue

    $perl $tg_reprocess $dir --dtffilter=0.9 2>&1 | tee $dir/tg_reprocess.log
    rm -f $outdir/*evt1{,_ssc,a}.fits
done
