#! /bin/bash

# for some reason this exits evt2_bin after the first bin
#set -e
set -o pipefail

# time parallel -j 32 ./0READMEs/03_README_binspec ::: $(obsids)

obsids="$@"

. ~/.bash_aliases
shopt -s expand_aliases

ciao -o

. src/functions.bash
. /data/legs/rpete/flight/analysis_functions/tmppdir.bash

for o in $obsids
do
    evt2_bin $datadir/$o/tg_reprocess/*_evt2.fits $datadir/$o/tg_reprocess/bin_400 400
done
