#! /bin/bash

. src/functions.bash

. ~/.bash_aliases
shopt -s expand_aliases

ciao -o

obsids=$(obsids)

for o in $obsids
do
    evt2_bin $datadir/$o/tg_reprocess/*_evt2.fits $datadir/$o/tg_reprocess/bin_400 400
done
