#! /bin/bash

set -eo pipefail

# time parallel -j 20 ./0READMEs/06_README_fluximg ::: $(obsids)

obsids="$@"

. ~/.bash_aliases
shopt -s expand_aliases

ciao -o

perl=/proj/axaf/bin/perl
[[ `hostname` = @(milagro|legs) ]] && perl=perl

base=/data/legs/rpete/data/ARLac

. /data/legs/rpete/flight/analysis_functions/tmppdir.bash
. /data/legs/rpete/flight/analysis_functions/caldb_files.bash

punlearn ardlib

i_qe=17
i_qe_dir=/data/legs/rpete/flight/hrci_qe/N00${i_qe}/qe

s_qe=17
s_qe_dir=/data/legs/rpete/flight/hrcs_qe/N00${s_qe}/qe

s_qeu=22
s_qeu_dir=/data/legs/rpete/flight/hrcs_qeu/ARD/v${s_qeu}/qeu

# Don't do this until all instrument maps are ready to be recreated
mkdir -p ./spectrum
# sherpa -b src/mkspectrum.py

for o in $obsids
do
    evt2=$(ls "$base/$o/tg_reprocess"/*_evt2.fits)
    detnam=$(dmkeypar "$evt2" detnam echo+)

    echo $detnam | grep -qi hrc-i && {
        i_qe_file=$(match_caldb_file "$evt2" qe "${i_qe_dir}" "N00${i_qe}")
        pset ardlib AXAF_HRC-I_QE_FILE="$i_qe_file"
    }

    echo $detnam | grep -qi hrc-s && {
        s_qe_file=$(match_caldb_file "$evt2" qe "${s_qe_dir}" "N00${s_qe}")
        pset ardlib AXAF_HRC-S1_QE_FILE="$s_qe_file"'[AXAF_QE1]'
        pset ardlib AXAF_HRC-S2_QE_FILE="$s_qe_file"'[AXAF_QE2]'
        pset ardlib AXAF_HRC-S3_QE_FILE="$s_qe_file"'[AXAF_QE3]'

        s_qeu_file=$(match_caldb_file "$evt2" qeu "$s_qeu_dir" "N00${s_qeu}")
        pset ardlib AXAF_HRC-S1_QEU_FILE="$s_qeu_file"'[AXAF_QEU1]'
        pset ardlib AXAF_HRC-S2_QEU_FILE="$s_qeu_file"'[AXAF_QEU2]'
        pset ardlib AXAF_HRC-S3_QEU_FILE="$s_qeu_file"'[AXAF_QEU3]'
    }

    indir=$base/$o
    rm -f "$indir"/cell_output.fits

    for id in ph erg
    do
	spectrumfile=/data/legs/rpete/flight/ARLac/spectrum/spectrum_${id}.txt

	outdir=$indir/flux_full
	mkdir -p $outdir
	$perl ./src/mkflux $indir \
	    --id=$id --spectrumfile=$spectrumfile \
	    --postfix 0 --outdir $outdir \
	    2>&1 | tee $outdir/flux_${id}_0.log

#	for t in 100 400
	for t in 400
	do
	    outdir=$indir/flux_$t
	    mkdir -p $outdir
	    $perl ./src/mkflux_binned $indir $t \
		--outdir=$outdir \
		-- \
		--id=$id --spectrumfile=$spectrumfile \
		2>&1 | tee $outdir/flux_${id}.log
	done
    done
done

#
# find obsids potentially affected by the HESF
#
false && {
  for o in $obsids
  do
    dmstat /data/legs/rpete/data/ARLac/$o/tg_reprocess/*evt2_dtffilt.fits'[sky=region(/data/legs/rpete/data/ARLac/'$o'/flux_full/src.reg)][col chip]' verbose=0
    xmin=`pget dmstat out_min | cut -f1 -d,`
    ymax=`pget dmstat out_max | cut -f2 -d,`
    [ $xmin -lt 1050 -a $ymax -gt 13000 ] && echo $o: $xmin $ymax
  done
}

# view counts images
false && {
    for o in $obsids
    do
        echo $o
        dir=/data/legs/rpete/data/ARLac/$o/flux_full
        ds9 \
            $dir/img_clean0.fits \
	    -cmap Heat \
	    -zoom to fit \
	    -scale log \
	    -scale mode 99.5 \
            -regions $dir/src.reg \
            -regions $dir/bg.reg
    done
}
