#! /bin/bash

set -e
set -o pipefail

outdir=./collected
mkdir -p "$outdir"

for det in hrci hrcs
do
    for id in erg ph
    do
	for s in 400 full
	do
	    rdball="$outdir/${det}_${s}_${id}.rdb"
            perl ./src/collect --$det --id=$id --subdir=flux_$s 2>&1 1>"$rdball"
	    rdbnobad="$outdir/${det}_${s}_${id}_nobad.rdb"
	    perl ./src/strip_bad.pl "$rdball" > "$rdbnobad"

	done
    done
done

# create observation list tables,
perl ./src/mk_obs_list > "$outdir/obstbl.rdb"
perl ./src/mk_obs_list --latex > "$outdir/obstbl.tex"
