#! /bin/bash

outdir=./collected
mkdir -p "$outdir"

for det in hrci hrcs
do
    for id in erg ph
    do
	for s in 400 full
	do

	    #
	    # perl 5.22.1 is now outputting annoying warnings
	    #
	    # Negative repeat count does nothing at Basic/Core/Core.pm.PL (i.e. PDL::Core.pm) line 1604.
	    #
	    # from the debugger, this is coming from
	    #
	    # PDL::dummy(Basic/Core/Core.pm.PL (i.e. PDL::Core.pm):1604):
	    # 1604:      $s .= '*1,' x ( $dim-$pdl->getndims );
	    #
	    # For now, just use shell ouput redirection to ignore the warning

	    rdball="$outdir/${det}_${s}_${id}.rdb"
	    rdbnobad="$outdir/${det}_${s}_${id}_nobad.rdb"

            perl ./src/collect --$det --id=$id --subdir=flux_$s 2>&1 1>"$rdball" #| grep -v 'Negative repeat'
	    perl ./src/strip_bad.pl "$rdball" > "$rdbnobad"

	done
    done
done

# create observation list tables,
perl ./src/mk_obs_list > "$outdir/obstbl.rdb"
perl ./src/mk_obs_list --latex > "$outdir/obstbl.tex"
