#! /bin/bash

set -e
set -o pipefail

outdir=./collected/plots
indir=./collected
mkdir -p "$outdir"

for det in hrci hrcs
do
    for id in erg ph
    do
	for i s in 400 full
	do

	    rdb="$indir/${det}_${s}_${id}.rdb"

	    fluxplot="$outdir/${det}_${s}_${id}"
	    rateplot="$outdir/${det}_${s}_rate"

	    title='AR Lac: HRC-S'
	    [ "$det" == "hrci" ] &&
                title='AR Lac: HRC-I'

	    echo "$rdb" $id $s 1>&2

            perl ./src/plotlc --title "$title" "$rdb" -dev "${fluxplot}.pdf"/pdf
            perl ./src/plotlc --noflare --title "$title" "$rdb" -dev "${fluxplot}_noflare.pdf"/pdf


	    [ "$id" == erg ] && {
	        perl ./src/plotlc --title "$title" "$rdb" -dev "${rateplot}.pdf"/pdf --rate
	        perl ./src/plotlc --noflare --title "$title" "$rdb" -dev "${rateplot}_noflare.pdf"/pdf --rate
            }
	    echo '' 1>&2
	done
    done
done

perl ./src/plotlc --title 'AR Lac: HRC' --iscale 0.86 ./collected/hrci_400_erg.rdb ./collected/hrcs_400_erg.rdb --noflare -dev $outdir/hrc_erg_noflare.pdf/pdf
